### ISSUE TITLE
검출 안 된 얼굴 살리기

### ISSUE THREAD

**Issue by kyukyukyu** [kyukyukyu/ugproj-detector#14]
얼굴이 하나도 검출되지 않은 프레임에서, 이전 프레임에서 검출된 face candidate들의 feature points를 기준으로 box fitting을 수행하여 얼굴을 살려내도록 구현. Face detection의 결과와 관계없이 association을 수행한다고 생각하면 될 듯.

**Comment by kyukyukyu** [comment]
일단은 `KltFaceAssociator::associate()` 을 호출하면 뒤 프레임의 face candidates(`FaceAssociator::nextCandidates`)를 채워 넣도록 구현할 생각이다. 하지만 이렇게 짜면 face associator를 사용하는 입장에서 association 연산을 수행하면서 뒤 프레임의 face candidates가 변경되는 것이 side-effect로 간주될 수 있다. 따라서, 추후에 리팩토링이 필요할 것이다. Box-fitting 및 best fit finding 하는 부분을 별도의 클래스로 분리하는 식으로 진행해야 할 것.

**Comment by kyukyukyu** [comment]
이런 문제들이...

## Optical flow length thresholding(issue #12)으로 해결 가능할 것 같은 경우

![262](https://cloud.githubusercontent.com/assets/1587211/8482165/bdfd0e8e-2122-11e5-9847-8dd990b19adc.png)
![264](https://cloud.githubusercontent.com/assets/1587211/8482166/be01e71a-2122-11e5-9339-ad073074a77f.png)
![535](https://cloud.githubusercontent.com/assets/1587211/8482177/d788d414-2122-11e5-9ca4-c05715bf75d6.png)
![538](https://cloud.githubusercontent.com/assets/1587211/8482178/d7892b58-2122-11e5-8a2a-0b48cb3c60a8.png)

## Scene change인데 비슷한 위치에 다른 사람 얼굴 나오는 경우

![343](https://cloud.githubusercontent.com/assets/1587211/8482123/730dbfd6-2122-11e5-890e-dc358ea51588.png)
![346](https://cloud.githubusercontent.com/assets/1587211/8482126/754717ca-2122-11e5-821a-74f1523275a5.png)

## Feature 재설정(issue #13)으로 해결 가능한 것 같은 경우

![773](https://cloud.githubusercontent.com/assets/1587211/8482219/21f02138-2123-11e5-818b-acfb4be35fe0.png)
![775](https://cloud.githubusercontent.com/assets/1587211/8482220/22009338-2123-11e5-804f-77aacc024b7d.png)

**Comment by kyukyukyu** [comment]
이슈 #12, #13 작업 내용이랑 합치면 다 잘 될 줄 알았는데 associator 구현에 문제가 있는 듯하다.

![118](https://cloud.githubusercontent.com/assets/1587211/8551136/bf304424-250f-11e5-8189-6f4d8f032fb7.png)
![120](https://cloud.githubusercontent.com/assets/1587211/8551137/bf34a668-250f-11e5-8f2c-4651f94dacf5.png)

![262](https://cloud.githubusercontent.com/assets/1587211/8551150/d425b864-250f-11e5-9ac9-a0dee275f63d.png)
![264](https://cloud.githubusercontent.com/assets/1587211/8551151/d428dae4-250f-11e5-8ae9-94ae398a2a73.png)

@na0126dud, 7월 7일 미팅에서 이 문제 해결하기 위한 방안으로 제시되었던 것들을 여기에 정리해주세요. 이 이슈가 아직 해결되지 않았으니 이슈를 새로 만들지 말고 comment로 정리하는 게 좋을 듯!

**Comment by Naing0126** [comment]
association하여 새로 만들어진 best fit box를 face candidate를 추가하였을 때의 문제를 해결하기 위해 고려해야 할 사항
1. best fit box를 고를 때, inlier의 개수를 threshold처리하여 너무 적은 inlier를 가지고 best fit box가 되는 경우를 방지
2. inlier를 결정하는 거리도 threshold로 섬세하게 처리하여 좀 더 정확한 inlier 확보
3. fit box가 너무 작은 경우에도 threshold처리

**Comment by kyukyukyu** [comment]
@na0126dud Git 작업 흐름 안내해드립니당.

작업 하기 전에,

``` shell
git checkout meeting-20150707  # meeting-20150707 브랜치로 checkout
git checkout -b meeting-20150714  # meeting-20150714 라는 브랜치 새로 만듦
git push origin meeting-20150714  # meeting-20150714 브랜치 push
git checkout -b issue-14  # 여기에서 issue-14 브랜치 땀
```

이제 작업 쭉쭉 하고,

``` shell
git checkout meeting-20150714  # meeting-20150714 브랜치로 checkout 하고
git pull origin meeting-20150714  # meeting-20150714 브랜치 내용 갱신 (@kyukyukyu가 작업 하지 않는 이상 갱신되는 게 없을 것임)
git checkout issue-14  # issue-14 브랜치로 체크아웃
git rebase meeting-20150714  # meeting-20150714 브랜치 내용 위에 rebase
```

만에 하나 @kyukyukyu가 작업을 해서 `meeting-20150714` 브랜치의 내용이 갱신됐는데, `issue-14` 브랜치의 작업 내용과 충돌이 생기면 이 시점에 해결해야 함. 해결을 마치고 나서,

``` shell
git checkout meeting-20150714
git merge issue-14  # meeting-20150714 브랜치의 작업 내용을 issue-14 브랜치의 작업 내용과 합침. Rebase를 했기 때문에 conflict이 발생하지 않고, fast-forward(merge commit 없는 merge)이 수행될 것이다.
git push origin meeting-20150714
```

하시면 됩니다.

**Comment by Naing0126** [comment]
엌..... 이제서야 봤다.. 걍 meeting-20150707에 작업하고 있었는데ㅠㅠ
commit 복사하는거 찾아볼게여ㅠ
일단 현재까지 제일 좋은 결과
![face_26](https://cloud.githubusercontent.com/assets/3378643/8635169/22c5e2ce-2852-11e5-9e29-277ea975e835.png)
