### ISSUE TITLE
Clustering face tracklet with k-means

### ISSUE THREAD

**Issue by kyukyukyu** [kyukyukyu/ugproj-detector#26]
이슈 #25 에 기술한 대로 각 face tracklet의 대표 이미지의 dimensionality를 감소시킨 결과를 가지고 k-means 사용하여 클러스터링.
OpenCV에서 제공하는 k-means API 사용할 것. [API 문서](http://docs.opencv.org/modules/core/doc/clustering.html?highlight=kmeans#kmeans) 참조.

**Comment by Naing0126** [comment]
configure 파일 좀 예제로 하나 올려주세여! 지금 갖고있는 건 Cluster부분이 없어서 에러가 뜨네요..

**Comment by kyukyukyu** [comment]
커밋 0e48f4565dc3f4d2be4afc95bc1951d13539244f 참조하세요~ `master` 브랜치에 올라가 있는 커밋입니다.
