### ISSUE TITLE
boost validate error

### ISSUE THREAD

**Issue by Naing0126** [kyukyukyu/ugproj-detector#28]
make 했을 때 다음과 같은 에러가 납니다..

naing@naing://home/naing/Documents/ugproj-detector/build$ make
Scanning dependencies of target ugproj
[ 16%] Building CXX object src/CMakeFiles/ugproj.dir/main.cc.o
//home/naing/Documents/ugproj-detector/src/main.cc:232:13: error: specialization of ‘template<class T, class charT> void boost::program_options::validate(boost::any&, const std::vectorstd::basic_string<charT >&, T_, long int)’ in different namespace [-fpermissive]
     long int) {
             ^
In file included from /usr/include/boost/program_options/value_semantic.hpp:418:0,
                 from /usr/include/boost/program_options/options_description.hpp:13,
                 from /usr/include/boost/program_options.hpp:15,/usr/include/boost/program_options/detail/value_semantic.hpp:82:10: error:   from definition of ‘template<class T, class charT> void boost::program_options::validate(boost::any&, const std::vectorstd::basic_string<charT >&, T_, long int)’ [-fpermissive]
     void validate(boost::any& v, 
          ^
//home/naing/Documents/ugproj-detector/src/main.cc:255:13: error: specialization of ‘template<class T, class charT> void boost::program_options::validate(boost::any&, const std::vectorstd::basic_string<charT >&, T_, long int)’ in different namespace [-fpermissive]
     long int) {
             ^
In file included from /usr/include/boost/program_options/value_semantic.hpp:418:0,
                 from /usr/include/boost/program_options/options_description.hpp:13,
                 from /usr/include/boost/program_options.hpp:15,
                 from //home/naing/Documents/ugproj-detector/src/main.cc:9:
/usr/include/boost/program_options/detail/value_semantic.hpp:82:10: error:   from definition of ‘template<class T, class charT> void boost::program_options::validate(boost::any&, const std::vectorstd::basic_string<charT >&, T_, long int)’ [-fpermissive]
     void validate(boost::any& v, 
          ^
make[2]: **\* [src/CMakeFiles/ugproj.dir/main.cc.o] Error 1
make[1]: **\* [src/CMakeFiles/ugproj.dir/all] Error 2
make: **\* [all] Error 2

왜그럴까요ㅠㅠ

**Comment by kyukyukyu** [comment]
Template specialization 관련해서 생기는 컴파일 에러인 거 같은데... clang에서는 문제없이 잘 되더니만 gcc에선 잘 안 되나 봅니다. 이 문제와 관련하여 [여기](http://stackoverflow.com/questions/3072248/why-arent-template-specializations-allowed-to-be-in-different-namespaces)를 참조하세요.

`src/main.cc` 파일의 226번째 줄부터 마지막 줄까지

``` cpp
namespace boost {
namespace program_options {
...
}   // program_options
}   // boost
```

블럭으로 감싸면 해결될 것 같습니다.

**Comment by Naing0126** [comment]
naing@naing://home/naing/Documents/ugproj-detector/build$ make
Scanning dependencies of target ugproj
[ 16%] Building CXX object src/CMakeFiles/ugproj.dir/main.cc.o
//home/naing/Documents/ugproj-detector/src/main.cc:234:13: error: explicit qualification in declaration of ‘void boost::program_options::validate(boost::any&, const std::vectorstd::basic_string<char >&, cv::Scalar_, long int)’
     long int) {
             ^
//home/naing/Documents/ugproj-detector/src/main.cc:257:13: error: explicit qualification in declaration of ‘void boost::program_options::validate(boost::any&, const std::vectorstd::basic_string<char >&, cv::Size_, long int)’
     long int) {
             ^
make[2]: **\* [src/CMakeFiles/ugproj.dir/main.cc.o] Error 1
make[1]: **\* [src/CMakeFiles/ugproj.dir/all] Error 2
make: **\* [all] Error 2
naing@naing://home/naing/Documents/ugproj-detector/build$ 

이 에러가 떠서 현재 해결해보는 중..

**Comment by kyukyukyu** [comment]
오류가 발생한 라인들에 있는 함수 정의에서

boost::program_options::

를 빼 보세요.

—

**Comment by Naing0126** [comment]
아 드디어 됐다ㅠㅠ
