### ISSUE TITLE
파일경로를 못읽어여ㅠ

### ISSUE THREAD

**Issue by Naing0126** [kyukyukyu/ugproj-detector#3]
build는 얼추 됐는데 비디오를 못읽네... 절대경로 상대경로 다 해봐도 안댐 ㅠㅠ

**Comment by kyukyukyu** [comment]
이거 아까 FFmepg 빌드 하고 FFmpeg 지원 옵션 먹여서 OpenCV 빌드 다시 해 보라고 말했는데 잘 됐는지 모르겠네.
해 보고 어떻게 됐는지 알려주세요~
