### ISSUE TITLE
Random으로 두 개 골라서 만든 fit box candidate 안에 match된 point가 하나도 없는 문제

### ISSUE THREAD

**Issue by Naing0126** [kyukyukyu/ugproj-detector#9]
![nomatchesinfitbox](https://cloud.githubusercontent.com/assets/3378643/7436022/391d6e58-f084-11e4-8d90-9018b49b42c2.PNG)

테스트하다가 먼가 이상해서 fit box candidate들 안에 각각 match된 쌍이 몇 개 들어가있는지 찍어봤는데 하나도 안들어가있는 경우가 많당ㅠㅠ

이게 random으로 두 개 정할때 match 쌍 중에서 2개 정하는거 아닌가?? 그럼 반드시 2개는 있어야 하는데 왜 하나도 없는 경우가 있지ㅠㅠ 저래서 best fit box에도 inlier가 0개 나오고 그런듯ㅠㅠ

나중에 참고해봅시다ㅠ

**Comment by kyukyukyu** [comment]
s, a, b는 맞게 구했는데 fit box 위치를 잘못 잡는 버그가 있었어. (!) 커밋 6585c39757b3048c5adf2ff03c2826d9afe77662 참조.

근데 이렇게 고쳐도 얼굴이 변형되는 경우가 translation과 uniform scale이 전부가 아니기 때문에 box fitting을 해도 inlier가 존재하지 않는 경우가 드물게 존재하긴 하더라고.
